### ISSUE TITLE
App currently displays as 'SignIn Activity' in the app drawer.

### ISSUE THREAD

**Issue by Jaredng** [CSE403FindersKeepers/finders-keepers#20] opened 2016-11-12 04:34 UTC
Currently, we're reporting to Android as the name of our parent activity, which is called 'SignInActivity'. This doesn't affect any functionality otherwise.

**Comment by dowelc** [comment] 2016-11-22 01:11
This is a duplicate of issue #10

**Closed by dowelc** 2016-11-22 01:11 UTC
Labels: app, bug, low severity
